# Generated by Django 4.0.1 on 2022-05-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='updated_date',
            new_name='uptated_date',
        ),
    ]
